[package]
name = "rsp2-kets"
version = "0.2.0-alpha1"
authors = ["Michael Lamparski <diagonaldevice@gmail.com>"]

[dependencies]
lazy_static = "0.2"
serde = { version = "1", optional = true, features = ["derive"] }
